// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvgwlGckfSTDIMRBBlgJXY9ahcDPicjr8',
    appId: '1:622031513482:web:e0e2d1dc061bbd7b250a73',
    messagingSenderId: '622031513482',
    projectId: 'push-notifications-flutt-26282',
    authDomain: 'push-notifications-flutt-26282.firebaseapp.com',
    storageBucket: 'push-notifications-flutt-26282.firebasestorage.app',
    measurementId: 'G-0GQJKS6SVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTpzio7H6TDrzH8jlMGgrtWPbcDjEl9q0',
    appId: '1:622031513482:android:5d7a27b3c47933b2250a73',
    messagingSenderId: '622031513482',
    projectId: 'push-notifications-flutt-26282',
    storageBucket: 'push-notifications-flutt-26282.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnwUGz9_jYtT-lnN56GeQD95FcUyF3HoM',
    appId: '1:622031513482:ios:dd63640b4f19f93a250a73',
    messagingSenderId: '622031513482',
    projectId: 'push-notifications-flutt-26282',
    storageBucket: 'push-notifications-flutt-26282.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnwUGz9_jYtT-lnN56GeQD95FcUyF3HoM',
    appId: '1:622031513482:ios:dd63640b4f19f93a250a73',
    messagingSenderId: '622031513482',
    projectId: 'push-notifications-flutt-26282',
    storageBucket: 'push-notifications-flutt-26282.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvgwlGckfSTDIMRBBlgJXY9ahcDPicjr8',
    appId: '1:622031513482:web:fcda961b0a61566c250a73',
    messagingSenderId: '622031513482',
    projectId: 'push-notifications-flutt-26282',
    authDomain: 'push-notifications-flutt-26282.firebaseapp.com',
    storageBucket: 'push-notifications-flutt-26282.firebasestorage.app',
    measurementId: 'G-CFRCF60X54',
  );
}
