export 'package:widgets_app/presentation/screens/app_tutorial/app_tutorial_screen.dart';
export 'package:widgets_app/presentation/screens/buttons/buttons_screen.dart';
export 'package:widgets_app/presentation/screens/cards/cards_screen.dart';
export 'package:widgets_app/presentation/screens/home/home_screen.dart';
export 'package:widgets_app/presentation/screens/inamated/animated_screen.dart';
export 'package:widgets_app/presentation/screens/inamated/animated_screen.dart';
export 'package:widgets_app/presentation/screens/infinite_scroll/infitite_scroll_screen.dart';
export 'package:widgets_app/presentation/screens/snackBar/snackBar_screen.dart';
export 'package:widgets_app/presentation/screens/ui_controls/ui_controls_screen.dart';
